#!/bin/bash

for SIZE in {0..299}; do
  start=$(date +%s%N)
  #./run DT ${SIZE}.mat 
  ~/Desktop/cmr/build/cmr-tu ~/Desktop/WeightedRectanglesPartition/matricesToTest/${SIZE}.mat 
  #unimodularity-test -t -q matricesToTest/${SIZE}.mat 
  end=$(date +%s%N)
  duration=$((end - start))
  echo "Execution time was ${duration} nanoseconds."
done > outputTU.txt 2>&1
